### ISSUE TITLE
Testing console.log 

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#24]
I'm trying to write a very simple plugin that outputs the type and path of event it receives. https://github.com/iilab/sigh-debug

When trying to write a test for it I've looked at this approach http://stackoverflow.com/a/24521132

This is [the relevant code](https://github.com/iilab/sigh-debug/blob/master/src/test/index.spec.js#L32)

The test fails with 
```
 * mocha: run tests in process 28461
 ! error: pipeline mocha
 ! Error: Unspecified AssertionError
```

I realise this is probably due more to my lack of experience in matching Promises, tests and the type of stubbing that Sinon does, but hopefully you can shed some lights!

**Comment by ohjames** [comment]
The problem here is you aren't providing any input files. The error is misleading, I'll create another issue for it.

**Comment by ohjames** [comment]
Oops sorry that message was meant for another commit. This error is related to mocha rather than sigh I think?

**Comment by ohjames** [comment]
Sorry I have no idea what's going wrong here, but I think your plugin should definitely work! Just gotta debug your mocha stuff more.
