### ISSUE TITLE
Please review sigh-pipe plugin

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#25]
Hi there,

I was in need of a plugin that would run a unix command for each file by piping their data into their stdin and updating them with the stdout results. That was for the hercule command https://github.com/jamesramsay/hercule which can surely be done - by someone with more skills - through the streaming API, but I thought that the general case of wrapping a unix command would actually be more useful to others.

So here it is https://www.npmjs.com/package/sigh-pipe

Would really appreciate your input!

Jun

**Comment by ohjames** [comment]
The github link is a 404 :baby_chick:

**Comment by jmatsushita** [comment]
Oops. I'll fix it on npm when I'm in front on my computer. Its https://github.com/contentascode/sigh-pipe

**Comment by ohjames** [comment]
Looks good to me, only I'd use const instead of var and be consistent with semicolon usage or lack thereof.
