### ISSUE TITLE
Source maps after multiple js transpilers are incorrect

### ISSUE THREAD

**Issue by Strate** [sighjs/sigh#30]
I am trying to implement this pipeline:

```
pipelines['build-ts'] = [
        glob({basePath: "src"}, "**/{*.ts,*.tsx}"),
        typescript(),
        babel6({babelrc: path.resolve("./.babelrc")}),
        write("target/src")
    ]
```
[sigh-typescript](https://github.com/Strate/sigh-typescript)
[sigh-babel6](https://github.com/Strate/sigh-babel6)

The one and only way to get sourcemaps points to original `ts` and `tsx` files is to explicit do [this](https://github.com/Strate/sigh-babel6/blob/master/src/index.js#L25) insdie compiler, am I right?

If I set `map.sources` to `[event.path]`, source maps targets to `js` and `jsx` files produced by `typescript`. Seems that managing sourcemaps with setting `sources` to `[event.path]` makes them pointing to latest compiler in pipeline.

Am I missing something?

**Comment by ohjames** [comment]
https://github.com/sighjs/sigh-babel/blob/master/src/index.js#L57

**Comment by ohjames** [comment]
Oh, you did that! Hm, will have to debug it more. I can help out at the weekend.

**Comment by ohjames** [comment]
Okay found the issue myself thanks to your help, will push he fix now. Thanks!

**Comment by unlight** [comment]
@Strate 
I've already implemented typescript plugin. But is simple, and has lack of settings.
https://github.com/unlight/sigh-ts

**Comment by Strate** [comment]
@unlight I used your plugin as a start point to write myself :-)

**Comment by ohjames** [comment]
Fixed via https://github.com/sighjs/sigh-core/commit/38dbaff0d2709e2b50ab0320b6689bdbd3426530
