### ISSUE TITLE
Pass through options to node-glob

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#37]
This is related to why I bumped into #36  

It would be good to pass the Options object key/values that are not Sigh specific down to [node-glob options](https://github.com/isaacs/node-glob#options).

In particular I'd like to have access to the 'ignore' option since otherwise (as far as I know) there is unnecessary walking at the globbing stage to exclude folders or files - if they needs to then be rejected afterwards with the sigh-reject/filter module.

**Comment by ohjames** [comment]
It might be better to add the option to the plugin and support each one explicitly, otherwise it will not be possible to switch out the glob implementation at a later date.

**Comment by ohjames** [comment]
Will close this for now, can open more specific issues for desired features.

**Comment by jamesj2** [comment]
Being able to pass the options to the node-glob is needed for ignoring specific patterns.  You can use select() to filter out the unwanted files but chokidar won't be filtered.  What about moving the watcher to it's own plugin so that users can supply their own options?

**Comment by ohjames** [comment]
I'm definitely open to a PR to add filter patterns, it's also fine to write other glob plugins that exist as plugins.

**Comment by ohjames** [comment]
Other plugins can check if `-w` was used to implement their own watch behaviour.
