### ISSUE TITLE
Implement `collectInitials` option for `merge`.

### ISSUE THREAD

**Issue by ohjames** [sighjs/sigh#46]
It will operate like https://github.com/Strate/sigh-await-and-merge

**Comment by Strate** [comment]
Related thing: filter plugin [emits Bacon.nothing() when array is empty](https://github.com/sighjs/sigh/blob/master/src/plugin/filter.js#L29), which gonna to be a problem with awaiting: if all events are filtered out on initial build phase, awaiting will never gonna end.

**Comment by ohjames** [comment]
That's a sigil and is flattened out.

**Comment by Strate** [comment]
Emitting empty array could be a solution.

**Comment by ohjames** [comment]
You don't understand: https://github.com/baconjs/bacon.js/#observable-flatmap

**Comment by Strate** [comment]
I can not understand why point me to that documentation section, but change line from `return events.length === 0 ? Bacon.never() : events` to `return events` does the job.

**Comment by Strate** [comment]
Ah, yeah, and change `flatMap` to `map` too :-)

**Comment by ohjames** [comment]
That piece of documentation explains it. If you can't even understand that then I have to question why you think you're informed enough to give me "advice" (which is all incorrect) on how to fix this.

It comes across as horribly arrogant. First do the research, then learn how to actually use the programming technique and APIs, and *then* you are qualified to give your opinion. Until then you're wasting everybody's time.

**Comment by ohjames** [comment]
That code is designed to only pass along the empty array in the case it is passed an empty array. If it filters a non-empty array to nothing then the event is hidden. It's clear that it's how it's designed to work if you understand `bacon.js`, `flatMap` exists to flatten event streams. As I said `Bacon.never()` is a sigil, it is never passed along.

**Comment by Strate** [comment]
I do understood that, thank you sir.
Do you close this issue because you won't to implement this thing?

**Comment by ohjames** [comment]
I just finished implementing it, will push soon!

**Comment by Strate** [comment]
One more thing. Why do you consider to hide event, instead of keeping it empty if it filtered out completely? Performance reasons?

**Comment by ohjames** [comment]
At the moment generally `[]` is used as an initialisation event (all streams receive it as the first event). It shouldn't hurt to just pass it down by itself though.

**Comment by ohjames** [comment]
First attempt in this commit: https://github.com/sighjs/sigh/commit/58f34318434e9c69e31b7665a234dbd871038e26

Haven't tested it yet.

**Comment by ohjames** [comment]
There it works now, is used as part of `sigh`'s own build process.
