### ISSUE TITLE
merge with collectInitial: true not propagating events?

### ISSUE THREAD

**Issue by joelanders** [sighjs/sigh#48]
```
    pipelines['two'] = [ 
        merge( {collectInitial: true},
            glob('A/*'),
            glob('B/*')
        ),  
        write('C')
    ]
```
The `write` plugin only sees events from the second `glob`.
With `collectInitial: false`, it sees events from both `glob`s (what I would expect in both cases).

**Comment by ohjames** [comment]
Released 0.12.29 with the fix.
