### ISSUE TITLE
rename sigh binary to sighjs, or rename sigh entirely

### ISSUE THREAD

**Issue by tcurdt** [sighjs/sigh#9]
I've already had clashes with another `sigh` binary.
Renaming the binary to `sighjs` would reduce the risk.

**Comment by ohjames** [comment]
A collision with https://github.com/KrauseFx/sigh ?

I've spoken to the author of that, he thought of the name `sigh` about 3 days before I did, strange coincidence. I guess I should rename sigh, and all of the sigh plugins etc.

Trying to think of another good name though, I like the name `sigh` :( Here are my candidates:
* worp
* turp
* torp
* tarp
* gah
* ohno
* belding

Any suggestions?

**Comment by ohjames** [comment]
I'll continue to support plugins named `sigh-` even after the name change.

**Comment by tcurdt** [comment]
Indeed - that's the project.

Frankly speaking I really like the name `sighjs`.
It is very in line with the search for a good tool for the job ;)
From that list `ohno` comes next for the very same reason :)
Next would be `gah`.

**Comment by ohjames** [comment]
I like the name `sigh` also, if only I'd created the first commit a few days earlier then I would have been first with it. Nope though, in all of the history of open source, two people selected the name a few days apart ;)

I've been delaying the name change until I can think of a name as good as `sigh` which may never happen. Actually I kinda want to call it `murder` after a `murder of crows` but yeah, society isn't ready for this brave naming.

**Comment by tcurdt** [comment]
Well, there is a project already https://github.com/lg/murder - and it's a pretty cool one :)

**Comment by tcurdt** [comment]
Another option would be to just call it through `npm run` and not use the global binary at all. Can't say I am a big fan of `npm i -g` anyway.
